# Generated by Django 3.2.6 on 2021-08-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_phrase', models.CharField(max_length=200, verbose_name='Frase en español')),
                ('english_phrase', models.CharField(blank=True, max_length=200, null=True, verbose_name='Frase en ingles')),
                ('learned', models.BooleanField(default=False, verbose_name='Frase aprendida?')),
                ('slug', models.SlugField(blank=True, null=True, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phrase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
                'ordering': ['-created'],
            },
        ),
    ]
