# Generated by Django 3.2.4 on 2021-06-08 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['-created'], 'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='phrase',
        ),
        migrations.AddField(
            model_name='phrase',
            name='english_phrase',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Frase en ingles'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='spanish_phrase',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Frase en español'),
            preserve_default=False,
        ),
    ]
