# Generated by Django 3.2.4 on 2021-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210608_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='learned',
            field=models.BooleanField(default=False, verbose_name='Frase aprendida?'),
        ),
    ]
