# Generated by Django 3.2.4 on 2021-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_dialogue', models.TextField(verbose_name='Frase en español')),
                ('english_dialogue', models.TextField(blank=True, null=True, verbose_name='Frase en ingles')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Dialogo',
                'verbose_name_plural': 'Dialogos',
                'ordering': ['-created'],
            },
        ),
    ]
